import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const gridStyle = {
    backgroundImage: `url("/gridPattern.svg")`, // Path to the SVG in your public folder
    backgroundRepeat: 'repeat',
    backgroundSize: '99px 99px',
  };

  return (
    <html lang="en">
      <body  style={gridStyle}
      >
        <Navbar/>
       <main> {children}</main>
      </body>
    </html>
  );
}
